generate:
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative mp_message/*.proto
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative order_state/*.proto
	protoc --proto_path=. --go_out=. --go_opt=paths=source_relative rating/*.proto
