
App:
  NameSpace:    prjc
  Name:         blog
  Service:      blog-restapi
  Environment:  local

API:
  Rest:
    Addr:         ":9000"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"
  Metrics:
    Addr:         ":9090"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"
  Probes:
    Addr:         ":9091"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"

Integration:
  CmcAPI:
    Httpconfig:
      Name:                 "cmc-api"
      MaxIdleConnDuration:  "60s"
      Timeout:              "120s"
      Host:                 "https://api.coinmarketcap.com"
    Cookie:  ""

  CmcProAPI:
    Httpconfig:
      Name:                 "cmc-pro-api"
      MaxIdleConnDuration:  "60s"
      Timeout:              "120s"
      Host:                 "https://pro-api.coinmarketcap.com"
    Token:  ""

  OraculAnalyticsAPI:
    Httpconfig:
      Name:                 "oracul-analytics-api"
      MaxIdleConnDuration:  "60s"
      Timeout:              "120s"
      Host:                 "https://api-v2.oracul.io"

Infra:
  TsDB:
    Conn:
      Host:             localhost
      Port:             5400
      User:             postgres
      DbName:           prjc
      SchemaName:       blog
      MaxOpenConns:     30
      MaxIdleConns:     30
      MinConns:         5
      MaxConnLifetime:  "1h"
      Timeout:          "60s"
    ReplicaSet:
      MasterHost:     "localhost"
      MasterPort:     5400
      SlaveHost:      "localhost"
      SlavePort:      5400
      Password:       "gjcnuhtc"

  Redis:
    Conn:
      Addrs:
        - "localhost:6379"
      Login:    ""
      Password: ""
      DBNum:    0
    ReplicaSet:
      MasterAddrs:    "localhost:6379"
      SlaveAddrs:     "localhost:6379"
      Password:       ""

Cli:
  CurrencyCollector:
    Duration:         "24h"
    PortfolioSourceIDs:
      - 6651f947db928013879d191c
    ListOfCurrencySlugs:
      - dogs
      - dydx-chain
      - dydx-ethdydx
      - mask-network
      - axelar
      - milady-meme-coin
      - magic-token
      - onbeam
      - echelon-prime
      - wootrade
      - apecoin-ape
      - camelot-token
      - unkjd
      - tribe
      - yield-guild-games
      - velodrome-finance
      - alchemix
      - liquity
      - hegic
      - torn
      - apex-token
      - hashflow
      - notcoin
      - wormhole
      - starknet-token
      - layerzero
      - space-id
      - green-metaverse-token
      - first-neiro-on-ethereum
      - uma
      - ssv-network
      - cow-protocol
      - altlayer
      - big-time
      - cyberconnect
      - maverick-protocol
      - sundog
      - vaderai-by-virtuals
      - luna-by-virtuals
      - big-time
      - pancakeswap
      - kaito
      - the-graph
      - immutable-x
      - optimism-ethereum
      - ethena
      - arbitrum
      - eigenlayer
      - aptos
      - avalanche
      - worldcoin-org
      - ondo-finance
      - pepe

