
App:
  NameSpace:    prjc
  Name:         blog
  Service:      blog-restapi
  Environment:  local

API:
  Rest:
    Addr:         ":9000"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"
  Metrics:
    Addr:         ":9090"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"
  Probes:
    Addr:         ":9091"
    ReadTimeout:  "5s"
    WriteTimeout: "5s"
    IdleTimeout:  "10s"

Integration:
  CmcAPI:
    Httpconfig:
      Name:                 "cmc-api"
      MaxIdleConnDuration:  "60s"
      Timeout:              "120s"
      Host:                 "https://api.coinmarketcap.com"
    Cookie:  ""

  CmcProAPI:
    Httpconfig:
      Name:                 "cmc-pro-api"
      MaxIdleConnDuration:  "60s"
      Timeout:              "120s"
      Host:                 "https://pro-api.coinmarketcap.com"
    Token:  ""

  OraculAnalyticsAPI:
    Httpconfig:
      Name:                 "oracul-analytics-api"
      MaxIdleConnDuration:  "60s"
      Timeout:              "120s"
      Host:                 "https://api-v2.oracul.io"

Infra:
  TsDB:
    Conn:
      Host:             localhost
      Port:             5400
      User:             postgres
      DbName:           prjc
      SchemaName:       blog
      MaxOpenConns:     30
      MaxIdleConns:     30
      MinConns:         5
      MaxConnLifetime:  "1h"
      Timeout:          "60s"
    ReplicaSet:
      MasterHost:     "localhost"
      MasterPort:     5400
      SlaveHost:      "localhost"
      SlavePort:      5400
      Password:       "gjcnuhtc"

  Redis:
    Conn:
      Addrs:
        - "localhost:6379"
      Login:    ""
      Password: ""
      DBNum:    0
    ReplicaSet:
      MasterAddrs:    "localhost:6379"
      SlaveAddrs:     "localhost:6379"
      Password:       ""

Cli:
  CurrencyCollector:
    Duration:         "24h"
    PortfolioSourceIDs:
      - 6651f947db928013879d191c
    ListOfCurrencySlugs:
      - dogs
      - dydx-chain
      - dydx-ethdydx
      - mask-network
      - axelar
      - milady-meme-coin
      - dogelon
      - synthetix
      - dexe
      - magic-token
      - onbeam
      - blur-token
      - meme
      - echelon-prime
      - wootrade
      - amp
      - aelf
      - apecoin-ape
      - orbs
      - swissborg
      - metisdao
      - camelot-token
      - gmx
      - telcoin
      - frax-share
      - unkjd
      - tribe
      - audius
      - civic
      - yield-guild-games
      - band-protocol
      - tokenlon-network-token
      - ontology
      - kwenta
      - spell-token
      - ontology-gas
      - stormx
      - velodrome-finance
      - whale
      - joe
      - superrare
      - api3
      - electroneum
      - celsius
      - status
      - radiant-capital
      - phala-network
      - looksrare
      - constellation
      - contentos
      - vite
      - mcdex
      - quarkchain
      - alchemix
      - cortex
      - pangolin
      - adx-net
      - metal
      - sentinel
      - unilend
      - keep3rv1
      - rally
      - loom-network
      - stargate-finance
      - edgeware
      - oax
      - liquity
      - radworks
      - hegic
      - combo-network
      - cream-finance
      - bytom
      - moviebloc
      - dfyn-network
      - nuls
      - airswap
      - aergo
      - paraswap
      - morpheus-network
      - ceek-vr
      - bitkan
      - augur
      - torn
      - dhedge-dao
      - unifi-protocol-dao
      - fusion
      - the-force-protocol
      - bella-protocol
      - barnbridge
      - pickle-finance
      - star-link
      - swftcoin
      - ren
      - idex
      - verasity
      - lambda
      - dforce
      - harvest-finance
      - apex-token
      - hashflow
      - powerpool
      - akropolis
      - morpho
      - notcoin
      - 0x
      - basic-attention-token
      - ftx-token
      - wormhole
      - starknet-token
      - 1inch
      - layerzero
      - space-id
      - ether-fi-ethfi
      - green-metaverse-token
      - biconomy
      - rocket-pool
      - first-neiro-on-ethereum
      - uma
      - ssv-network
      - cow-protocol
      - altlayer
      - balancer
      - illuvium
      - big-time
      - marlin
      - dkargo
      - aurora-near
      - cyberconnect
      - catizen
      - maverick-protocol
      - sundog
      - renzo
      - vaderai-by-virtuals
      - tokemak
      - paid-network
      - luna-by-virtuals
      - dora-factory-new
      - guild-of-guardians
      - heroes-of-mavia
      - taocat-by-virtuals-masa
      - aixcb-by-virtuals
      - unibot-eth
      - crustnetwork
      - meta
      - jetton
      - free-coin
      - dkargo
      - marlin
      - big-time
      - pancakeswap
      - kaito
      - agoras-tokens
      - vertex-protocol
      - wink
      - numeraire
      - cartesi
      - celer-network
      - constitutiondao
      - vvs-finance
      - the-graph
      - immutable-x
      - optimism-ethereum

