// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rating/rating.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	SellerName           string               `protobuf:"bytes,15,opt,name=SellerName,proto3" json:"SellerName,omitempty"`
	Rating               float64              `protobuf:"fixed64,2,opt,name=Blog,proto3" json:"Blog,omitempty"`
	RatioDelivered       float64              `protobuf:"fixed64,3,opt,name=RatioDelivered,proto3" json:"RatioDelivered,omitempty"`
	RatioDefected        float64              `protobuf:"fixed64,4,opt,name=RatioDefected,proto3" json:"RatioDefected,omitempty"`
	BuyerRatingWeight    float64              `protobuf:"fixed64,12,opt,name=BuyerRatingWeight,proto3" json:"BuyerRatingWeight,omitempty"`
	AvgBuyerRating       float64              `protobuf:"fixed64,6,opt,name=AvgBuyerRating,proto3" json:"AvgBuyerRating,omitempty"`
	SellerOldId          uint64               `protobuf:"varint,1,opt,name=SellerOldId,proto3" json:"SellerOldId,omitempty"`
	NbDelivered          uint64               `protobuf:"varint,10,opt,name=NbDelivered,proto3" json:"NbDelivered,omitempty"`
	NbInDelivery         uint64               `protobuf:"varint,11,opt,name=NbInDelivery,proto3" json:"NbInDelivery,omitempty"`
	NbOrdersMarketplace  uint64               `protobuf:"varint,9,opt,name=NbOrdersMarketplace,proto3" json:"NbOrdersMarketplace,omitempty"`
	NbBuyerRatings       uint64               `protobuf:"varint,5,opt,name=NbBuyerRatings,proto3" json:"NbBuyerRatings,omitempty"`
	NbDefected           uint64               `protobuf:"varint,13,opt,name=NbDefected,proto3" json:"NbDefected,omitempty"`
	NbOrdersTotal        uint64               `protobuf:"varint,14,opt,name=NbOrdersTotal,proto3" json:"NbOrdersTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b10cb65c5394aa1, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Blog) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Blog) GetSellerName() string {
	if m != nil {
		return m.SellerName
	}
	return ""
}

func (m *Blog) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Blog) GetRatioDelivered() float64 {
	if m != nil {
		return m.RatioDelivered
	}
	return 0
}

func (m *Blog) GetRatioDefected() float64 {
	if m != nil {
		return m.RatioDefected
	}
	return 0
}

func (m *Blog) GetBuyerRatingWeight() float64 {
	if m != nil {
		return m.BuyerRatingWeight
	}
	return 0
}

func (m *Blog) GetAvgBuyerRating() float64 {
	if m != nil {
		return m.AvgBuyerRating
	}
	return 0
}

func (m *Blog) GetSellerOldId() uint64 {
	if m != nil {
		return m.SellerOldId
	}
	return 0
}

func (m *Blog) GetNbDelivered() uint64 {
	if m != nil {
		return m.NbDelivered
	}
	return 0
}

func (m *Blog) GetNbInDelivery() uint64 {
	if m != nil {
		return m.NbInDelivery
	}
	return 0
}

func (m *Blog) GetNbOrdersMarketplace() uint64 {
	if m != nil {
		return m.NbOrdersMarketplace
	}
	return 0
}

func (m *Blog) GetNbBuyerRatings() uint64 {
	if m != nil {
		return m.NbBuyerRatings
	}
	return 0
}

func (m *Blog) GetNbDefected() uint64 {
	if m != nil {
		return m.NbDefected
	}
	return 0
}

func (m *Blog) GetNbOrdersTotal() uint64 {
	if m != nil {
		return m.NbOrdersTotal
	}
	return 0
}

func init() {
	proto.RegisterType((*Blog)(nil), "rating.Blog")
}

func init() {
	proto.RegisterFile("course/rating.proto", fileDescriptor_1b10cb65c5394aa1)
}

var fileDescriptor_1b10cb65c5394aa1 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4b, 0xfb, 0x30,
	0x14, 0xc0, 0xe9, 0xf7, 0x3b, 0x2b, 0xcb, 0x7e, 0x88, 0x19, 0xc8, 0x63, 0x07, 0x2d, 0x43, 0xa4,
	0x07, 0x69, 0x45, 0x2f, 0x5e, 0x1d, 0x5e, 0x76, 0xb0, 0x83, 0x3a, 0x10, 0xbc, 0xa5, 0xeb, 0x5b,
	0x2d, 0x66, 0x6d, 0xc9, 0xb2, 0xc1, 0xfe, 0x21, 0xff, 0x4e, 0x49, 0xd2, 0xba, 0x74, 0x7a, 0x6a,
	0xf3, 0x79, 0x9f, 0xe4, 0xe5, 0xbd, 0x3c, 0x32, 0x12, 0x4c, 0xe6, 0x45, 0x16, 0x9a, 0x4f, 0x50,
	0x89, 0x52, 0x96, 0xd4, 0x35, 0xab, 0xf1, 0x55, 0x56, 0x96, 0x19, 0xc7, 0x50, 0xd3, 0x64, 0xbb,
	0x0a, 0x65, 0xbe, 0xc6, 0x8d, 0x64, 0xeb, 0xca, 0x88, 0x93, 0xaf, 0x0e, 0x71, 0x63, 0xed, 0xd2,
	0x47, 0xd2, 0x5d, 0x34, 0x51, 0x38, 0xf5, 0x1c, 0xbf, 0x77, 0x3f, 0x0e, 0xcc, 0xfe, 0xa0, 0xd9,
	0x1f, 0xfc, 0x18, 0xf1, 0x41, 0xa6, 0x97, 0x84, 0xbc, 0x22, 0xe7, 0x28, 0x22, 0xb6, 0x46, 0x38,
	0xf3, 0x1c, 0xbf, 0x1b, 0x5b, 0x84, 0x5e, 0x34, 0x39, 0xe0, 0x9f, 0xe7, 0xf8, 0x4e, 0xdc, 0x64,
	0xbc, 0x21, 0x43, 0xf5, 0x57, 0x3e, 0x23, 0xcf, 0x77, 0x28, 0x30, 0x85, 0xff, 0x3a, 0x7e, 0x44,
	0xe9, 0x35, 0x19, 0xd4, 0x64, 0x85, 0x4b, 0x89, 0x29, 0x74, 0xb4, 0xd6, 0x86, 0xf4, 0x96, 0x9c,
	0x4f, 0xb7, 0x7b, 0x14, 0xe6, 0xf0, 0x37, 0xcc, 0xb3, 0x0f, 0x09, 0x7d, 0x6d, 0xfe, 0x0e, 0xa8,
	0xdc, 0x4f, 0xbb, 0xcc, 0xe2, 0xe0, 0x9a, 0xdc, 0x6d, 0x4a, 0x3d, 0xd2, 0x33, 0x95, 0xcc, 0x79,
	0x3a, 0x4b, 0xc1, 0xf1, 0x1c, 0xbf, 0x13, 0xdb, 0x48, 0x19, 0x51, 0x72, 0x28, 0x81, 0x18, 0xc3,
	0x42, 0x74, 0x42, 0xfa, 0x51, 0x32, 0x2b, 0x6a, 0xb0, 0x87, 0x9e, 0x56, 0x5a, 0x8c, 0xde, 0x91,
	0x51, 0x94, 0xcc, 0x45, 0x8a, 0x62, 0xf3, 0xc2, 0xc4, 0x27, 0xca, 0x8a, 0xb3, 0x25, 0x42, 0x57,
	0xab, 0x7f, 0x85, 0x54, 0x05, 0x51, 0x62, 0x5d, 0x75, 0x03, 0x27, 0x5a, 0x3e, 0xa2, 0xea, 0x75,
	0xd4, 0x65, 0xea, 0xd6, 0x0d, 0xb4, 0x63, 0x11, 0xd5, 0xdd, 0xe6, 0xf8, 0x45, 0x29, 0x19, 0x87,
	0xa1, 0x56, 0xda, 0x70, 0x3a, 0x79, 0xf7, 0xea, 0x41, 0xcb, 0x0b, 0x89, 0xa2, 0x60, 0x3c, 0x64,
	0x55, 0x65, 0x06, 0xab, 0x9e, 0xbd, 0xc4, 0xd5, 0xab, 0x87, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x0a, 0x09, 0x6f, 0x93, 0x02, 0x00, 0x00,
}
