apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://prometheus:9090

  - name: TimescaleDB
    type: postgres
    url: tsdb:5432
    database: prjc
    user: postgres
    secureJsonData:
      password: 'gjcnuhtc'
    isDefault: true
    jsonData:
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 0
      maxIdleConns: 100
      #maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true